# Generated by Django 6.0.2 on 2026-02-10 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moeda', models.CharField(choices=[('USD', 'Dólar (US$)'), ('PYG', 'Guarani (₲)')], max_length=3)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('casa_cambio', models.CharField(max_length=100)),
                ('melhor_cotacao', models.BooleanField(default=False)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PontoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='pontos_historicos/')),
                ('audio_guia', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('localizacao_url', models.URLField(help_text='Link do Google Maps', max_length=500)),
                ('categoria', models.CharField(choices=[('HISTORIA', 'História Local'), ('CULTURA', 'Cultura e Tradição'), ('ROTEIRO', 'Roteiro Acessível (Idosos)')], max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaColaborativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'História dos Usuários',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho_fonte', models.CharField(choices=[('normal', 'Normal'), ('grande', 'Grande'), ('extra', 'Extra Grande')], default='normal', max_length=20)),
                ('alto_contraste', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
