# Generated by Django 6.0.2 on 2026-02-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='tamanho_fonte',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fonte_grande',
            field=models.BooleanField(default=False),
        ),
    ]
