# Generated by Django 6.0.2 on 2026-02-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0002_remove_perfilusuario_tamanho_fonte_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontohistorico',
            options={'ordering': ['ordem', 'titulo'], 'verbose_name': 'Ponto Histórico/Cultural'},
        ),
        migrations.AddField(
            model_name='pontohistorico',
            name='ordem',
            field=models.IntegerField(default=0, help_text='Quanto menor o número, mais no topo aparece'),
        ),
        migrations.AddField(
            model_name='pontohistorico',
            name='subtitulo',
            field=models.CharField(blank=True, help_text='Ex: O Gigante do Agronegócio', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pontohistorico',
            name='categoria',
            field=models.CharField(choices=[('AGRICULTURA', 'Cultura e Agricultura (Cards)'), ('TRAJETORIA', 'Nossa Trajetória (Details/Sanfona)'), ('ROTEIRO', 'Roteiro Acessível (Idosos)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pontohistorico',
            name='descricao',
            field=models.TextField(help_text='Conteúdo principal do texto'),
        ),
        migrations.AlterField(
            model_name='pontohistorico',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='pontos_historicos/'),
        ),
        migrations.AlterField(
            model_name='pontohistorico',
            name='localizacao_url',
            field=models.URLField(blank=True, help_text='Link do Google Maps', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pontohistorico',
            name='titulo',
            field=models.CharField(help_text='Ex: Soja ou As Raízes Indígenas', max_length=200),
        ),
    ]
