# Generated by Django 6.0.2 on 2026-02-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0003_alter_pontohistorico_options_pontohistorico_ordem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontohistorico',
            name='categoria',
            field=models.CharField(choices=[('Culturas', 'Culturas'), ('TRAJETORIA', 'Trajetória '), ('ROTEIRO', 'Roteiro Acessível (Idosos)')], max_length=20),
        ),
    ]
