# Generated by Django 6.0.2 on 2026-02-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0005_alter_pontohistorico_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontohistorico',
            name='categoria',
            field=models.CharField(choices=[('CULTURAS', 'Culturas'), ('HISTORIAS', 'Historias')], max_length=20),
        ),
    ]
