# Generated by Django 6.0.2 on 2026-02-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0006_alter_pontohistorico_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiacolaborativa',
            options={'ordering': ['-data_envio'], 'verbose_name': 'História dos Usuários', 'verbose_name_plural': 'Histórias dos Usuários'},
        ),
    ]
